require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SiteEnvironmentsController do

  # This should return the minimal set of attributes required to create a valid
  # SiteEnvironment. As you add validations to SiteEnvironment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SiteEnvironmentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all site_environments as @site_environments" do
      site_environment = SiteEnvironment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:site_environments).should eq([site_environment])
    end
  end

  describe "GET show" do
    it "assigns the requested site_environment as @site_environment" do
      site_environment = SiteEnvironment.create! valid_attributes
      get :show, {:id => site_environment.to_param}, valid_session
      assigns(:site_environment).should eq(site_environment)
    end
  end

  describe "GET new" do
    it "assigns a new site_environment as @site_environment" do
      get :new, {}, valid_session
      assigns(:site_environment).should be_a_new(SiteEnvironment)
    end
  end

  describe "GET edit" do
    it "assigns the requested site_environment as @site_environment" do
      site_environment = SiteEnvironment.create! valid_attributes
      get :edit, {:id => site_environment.to_param}, valid_session
      assigns(:site_environment).should eq(site_environment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SiteEnvironment" do
        expect {
          post :create, {:site_environment => valid_attributes}, valid_session
        }.to change(SiteEnvironment, :count).by(1)
      end

      it "assigns a newly created site_environment as @site_environment" do
        post :create, {:site_environment => valid_attributes}, valid_session
        assigns(:site_environment).should be_a(SiteEnvironment)
        assigns(:site_environment).should be_persisted
      end

      it "redirects to the created site_environment" do
        post :create, {:site_environment => valid_attributes}, valid_session
        response.should redirect_to(SiteEnvironment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved site_environment as @site_environment" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteEnvironment.any_instance.stub(:save).and_return(false)
        post :create, {:site_environment => { "name" => "invalid value" }}, valid_session
        assigns(:site_environment).should be_a_new(SiteEnvironment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SiteEnvironment.any_instance.stub(:save).and_return(false)
        post :create, {:site_environment => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested site_environment" do
        site_environment = SiteEnvironment.create! valid_attributes
        # Assuming there are no other site_environments in the database, this
        # specifies that the SiteEnvironment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SiteEnvironment.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => site_environment.to_param, :site_environment => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested site_environment as @site_environment" do
        site_environment = SiteEnvironment.create! valid_attributes
        put :update, {:id => site_environment.to_param, :site_environment => valid_attributes}, valid_session
        assigns(:site_environment).should eq(site_environment)
      end

      it "redirects to the site_environment" do
        site_environment = SiteEnvironment.create! valid_attributes
        put :update, {:id => site_environment.to_param, :site_environment => valid_attributes}, valid_session
        response.should redirect_to(site_environment)
      end
    end

    describe "with invalid params" do
      it "assigns the site_environment as @site_environment" do
        site_environment = SiteEnvironment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteEnvironment.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_environment.to_param, :site_environment => { "name" => "invalid value" }}, valid_session
        assigns(:site_environment).should eq(site_environment)
      end

      it "re-renders the 'edit' template" do
        site_environment = SiteEnvironment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SiteEnvironment.any_instance.stub(:save).and_return(false)
        put :update, {:id => site_environment.to_param, :site_environment => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested site_environment" do
      site_environment = SiteEnvironment.create! valid_attributes
      expect {
        delete :destroy, {:id => site_environment.to_param}, valid_session
      }.to change(SiteEnvironment, :count).by(-1)
    end

    it "redirects to the site_environments list" do
      site_environment = SiteEnvironment.create! valid_attributes
      delete :destroy, {:id => site_environment.to_param}, valid_session
      response.should redirect_to(site_environments_url)
    end
  end

end
